apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
      - name: product
        image: iampoonamhajare/product-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5001
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "200m"
